source "https://rubygems.org"

gem 'jekyll', '= 3.5.1' # locked in for stability.
gem 'jekyll-theme-simple-texture'

group :jekyll_plugins do
  gem 'jekyll-feed'
  gem 'jekyll-redirect-from'
  gem 'jekyll-seo-tag'
  gem 'jekyll-sitemap'
end
